
name: Build WebGoat with Maven
on:  
  push:
    branches-ignore: [ master ]
  pull_request:   
    branches-ignore: [ master ]

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
  security-events: write

jobs: 
  build-jdk8:
    runs-on: ${{ matrix.os }}
    strategy:
     max-parallel: 3
     fail-fast: false
     #GitHub-hosted runners, possible to add: windows-latest
     matrix:
       os: [ubuntu-latest]
          
    name: Configure Runner
    steps:
    - name: Checkout
      uses: actions/checkout@v4
         
    - name: Setup JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: 21

    - name: Setup JFrog CLI
      uses: jfrog/setup-jfrog-cli@v4
      id: setup-cli
      env:
        # JFrog platform url (for example: https://acme.jfrog.io)
        JF_URL: https://${{ vars.JF_URL }}/
        JF_PROJECT: ${{ vars.JF_PROJECT }}
      with:
        oidc-provider-name: mikeho-github
        version: latest

    - uses: s4u/maven-settings-action@v3.1.0
      with:
        servers: |
          [{
              "id": "${{ vars.JF_URL }}",
              "username": "${{ steps.setup-cli.outputs.oidc-user }}",
              "password": "${{ steps.setup-cli.outputs.oidc-token }}"
          }]
        
    - name: Ping Artifactory
      run: jf rt ping

    - if: always()   
      name: Feature Branch Repository Update
      run: |
        jf mvnc --repo-resolve-releases=mikeho-dev-webgoat-libs-release --repo-resolve-snapshots=mikeho-dev-webgoat-libs-snapshot --repo-deploy-releases=mikeho-dev-webgoat-libs-release --repo-deploy-snapshots=mikeho-dev-webgoat-libs-snapshot

    - name: Spotless Run
      run: |
        mvn spotless:apply
     
    - if: always()
      name: Build & Deploy
      run: | 
        jf mvn clean install 
        
    - if: always() 
      name: Publish Build Information
      run: |
        # Collect environment variables for the build
        jf rt build-collect-env
        # Adding Files as Build Dependencies
        jf rt build-add-dependencies .
        # Collect VCS details from git and add them to the build
        jf rt build-add-git
        # Publish build info
        jf rt build-publish       
        
    - if: always()
      name: Xray Build Scan
      run: |
        jf build-scan 
        jf audit

    - name: Run JFrog SAST
      run: |
        jf audit --sast --format=sarif > jfrog_sast.sarif

    - name: Upload output to generate autofix
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: jfrog_sast.sarif
        
    - name: Write to workflow job summary
      run: |
            NOTE=$'>[!NOTE]\n>Frog Notes \n'
            TIP=$'>[!TIP]\n>Hello JFrog\n'
            IMPORTANT=$'>[!IMPORTANT]\n>Hello IMPORTANT NOTE\n'
            WARNING=$'>[!WARNING]\n>Hello WARNING NOTE\n'
            CAUTION=$'>[!CAUTION]\n>Hello CAUTION NOTE\n'
            echo "$NOTE" >> $GITHUB_STEP_SUMMARY
            echo "$TIP" >> $GITHUB_STEP_SUMMARY
            echo "$IMPORTANT" >> $GITHUB_STEP_SUMMARY
            echo "$WARNING" >> $GITHUB_STEP_SUMMARY
            echo "$CAUTION" >> $GITHUB_STEP_SUMMARY
