name: "JFrog Webgoat CLI Example"
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.1
    
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          # JFrog platform url (for example: https://acme.jfrog.io)
          JF_URL: ${{ secrets.JF_URL }}

          # JFrog Platform access token
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

          # Basic authentication credentials
          ## JF_USER: ${{ secrets.JF_USER }}
          ## JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

      - name: Setup JDK 1.8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      #- name: Cache Maven packages
      #  id: cache
      #  uses: actions/cache@v2
      #  with:
      #    path: ~/.m2
      #    key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #    restore-keys: ${{ runner.os }}-m2

      - name: Setup settings.xml
        uses: s4u/maven-settings-action@v2.4.1
        with:
          repositories: | 
            [
              {"id":"snapshots","name":"dev-webgoat-libs-snapshot","url":"https://jfrogmikeho.jfrog.io/artifactory/dev-webgoat-libs-snapshot","username": "mikeho@jfrog.com", "password": "${{ secrets.JF_ACCESS_TOKEN }}","snapshots":{"enabled":true}},
              {"id":"central","name":"dev-webgoat-libs-snapshot","url":"https://jfrogmikeho.jfrog.io/artifactory/dev-webgoat-libs-snapshot","username": "mikeho@jfrog.com", "password": "${{ secrets.JF_ACCESS_TOKEN }}","snapshots":{"enabled":false}}
            ]
            
      - name: Build with Maven
        run: jf mvn clean install deploy -B "-DcustomVersion=${{ steps.branch-name.outputs.current_branch }}-${{ github.run_number }}"

      - name: Run JFrog CLI
        run: |
          # Ping the server
          jf rt ping
          # Collect environment variables for the build
          jf rt bce
          # Collect VCS details from git and add them to the build
          jf rt bag
          # Xray Scan
          # jf bs
          # Publish build info
          jf rt bp
